baseURL: "" 
title: Odette Rios-Ibacache
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About me
          url: About me/
        - name: CV
          url: CV/
          weight: 5 
        - name: Publications
          url: Publications/
          weight: 2

params:
    description: "I am Odette Rios-Ibacache, a PhD student in Medical Physics"
    author: Odette Rios-Ibacache
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["About me","CV","Publications"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Odette Rios-Ibacache
          subtitle: "Hi! I am a PhD student in Medical Physics at McGill University since September 2024. My research focuses on software development, radiation oncology informatics, and applications of Artificial Intelligence tools for Radiotherapy outcomes prediction and diagnosis. Currently, I work under the supervision of Prof. John Kildea, in his ROKS team."
          imageUrl: "Picture9.jpg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: About me
              url: About me/
            - name: CV
              url: CV/
            - name: Publications
              url: Publications/    
       
    socialIcons:
        - name: CV
          url: CV_Odette_Rios_Ibacache_Updated.pdf
        - name: Email
          URL: "odette.riosibacache@mail.mcgill.ca"
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=wSukTTIAAAAJ&hl=en
        - name: LinkedIn
          url: https://www.linkedin.com/in/odette-rios-ibacache-bb5947215/
        - name: ORCID
          url: https://orcid.org/0009-0003-9254-5592 


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Odette Rios-Ibacache"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
